import base64
import hashlib
import hmac
import json
import os
from datetime import datetime, timezone

from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding, rsa

from config import get_settings


def generate_report_hash(report_data: dict) -> dict:
    """
    Produces a deterministic SHA-256 hash of the report content.
    Sorts keys before hashing so field ordering cannot affect the hash.
    """
    clean_data = {
        key: value
        for key, value in report_data.items()
        if key not in ("_signature", "_hash_info")
    }
    canonical = json.dumps(clean_data, sort_keys=True, separators=(",", ":"), default=str)
    sha256_hash = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
    generated_at = datetime.now(timezone.utc).isoformat()
    return {
        "sha256": sha256_hash,
        "generated_at": generated_at,
        "algorithm": "SHA-256",
        "canonical_form": canonical,
        "canonical_length_bytes": len(canonical.encode("utf-8")),
    }


def generate_hmac_signature(sha256_hash: str, timestamp: str) -> str:
    """
    Signs hash + timestamp with REPORT_SIGNING_KEY.
    Returns base64-encoded HMAC-SHA256 signature string.
    """
    settings = get_settings()
    signing_key = settings.report_signing_key
    if not signing_key:
        signing_key = "LENDSYNTHETIX_DEV_KEY_CHANGE_IN_PROD"

    message = f"{sha256_hash}:{timestamp}".encode("utf-8")
    sig = hmac.new(signing_key.encode("utf-8"), message, hashlib.sha256).digest()
    return base64.b64encode(sig).decode("utf-8")


def build_verification_payload(report_data: dict, collection_name: str) -> dict:
    """
    Master function — call this once per report.
    Returns complete verification block to embed in the PDF.
    """
    hash_info = generate_report_hash(report_data)
    signature = generate_hmac_signature(hash_info["sha256"], hash_info["generated_at"])

    final_rec = (report_data.get("final_decision") or {}).get(
        "final_recommendation", "UNKNOWN"
    )
    risk_score = (report_data.get("risk_score") or {}).get("risk_score", "N/A")

    return {
        "document_id": f"LSX-{hash_info['sha256'][:12].upper()}",
        "collection_name": collection_name,
        "final_recommendation": final_rec,
        "risk_score": risk_score,
        "sha256_hash": hash_info["sha256"],
        "generated_at": hash_info["generated_at"],
        "algorithm": "HMAC-SHA256",
        "server_signature": signature,
        "canonical_length": hash_info["canonical_length_bytes"],
        "verification_note": (
            "This document was generated by LendSynthetix AI Credit "
            "War Room. To verify integrity, recompute SHA-256 of the "
            "canonical JSON and validate the HMAC signature against "
            "the issuing server secret."
        ),
    }
